# Generated by Django 5.2.5 on 2025-08-20 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyinventory',
            name='pharmacy',
            field=models.ForeignKey(help_text='Pharmacy that owns this inventory item', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='users.pharmacy'),
        ),
        migrations.AddIndex(
            model_name='medicinecategory',
            index=models.Index(fields=['name'], name='idx_category_name'),
        ),
        migrations.AddIndex(
            model_name='medicinecategory',
            index=models.Index(fields=['parent_category'], name='idx_category_parent'),
        ),
        migrations.AddIndex(
            model_name='medicinecategory',
            index=models.Index(fields=['is_active'], name='idx_category_active'),
        ),
        migrations.AddIndex(
            model_name='medicinecategory',
            index=models.Index(fields=['sort_order'], name='idx_category_sort'),
        ),
        migrations.AddIndex(
            model_name='medicinecatalog',
            index=models.Index(fields=['name'], name='idx_medicine_name'),
        ),
        migrations.AddIndex(
            model_name='medicinecatalog',
            index=models.Index(fields=['category'], name='idx_medicine_category'),
        ),
        migrations.AddIndex(
            model_name='medicinecatalog',
            index=models.Index(fields=['form'], name='idx_medicine_form'),
        ),
        migrations.AddIndex(
            model_name='medicinecatalog',
            index=models.Index(fields=['is_active'], name='idx_medicine_active'),
        ),
        migrations.AddIndex(
            model_name='medicinecatalog',
            index=models.Index(fields=['prescription_required'], name='idx_medicine_prescription'),
        ),
        migrations.AddConstraint(
            model_name='medicinecatalog',
            constraint=models.UniqueConstraint(fields=('name', 'form', 'dosage'), name='unique_medicine_combination'),
        ),
        migrations.AddIndex(
            model_name='pharmacyinventory',
            index=models.Index(fields=['pharmacy'], name='idx_inventory_pharmacy'),
        ),
        migrations.AddIndex(
            model_name='pharmacyinventory',
            index=models.Index(fields=['medicine'], name='idx_inventory_medicine'),
        ),
        migrations.AddIndex(
            model_name='pharmacyinventory',
            index=models.Index(fields=['category'], name='idx_inventory_category'),
        ),
        migrations.AddIndex(
            model_name='pharmacyinventory',
            index=models.Index(fields=['is_available'], name='idx_inventory_available'),
        ),
        migrations.AddIndex(
            model_name='pharmacyinventory',
            index=models.Index(fields=['price'], name='idx_inventory_price'),
        ),
        migrations.AddIndex(
            model_name='pharmacyinventory',
            index=models.Index(fields=['is_on_sale'], name='idx_inventory_sale'),
        ),
        migrations.AddConstraint(
            model_name='pharmacyinventory',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='valid_inventory_price'),
        ),
        migrations.AddConstraint(
            model_name='pharmacyinventory',
            constraint=models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='valid_stock_quantity'),
        ),
        migrations.AddConstraint(
            model_name='pharmacyinventory',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percentage__isnull', True), models.Q(('discount_percentage__gte', 0), ('discount_percentage__lte', 100)), _connector='OR'), name='valid_discount_percentage'),
        ),
    ]
