# Generated by Django 5.2.5 on 2025-08-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the delivery zone', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the delivery zone')),
                ('center_latitude', models.DecimalField(decimal_places=8, help_text='Center latitude of the delivery zone', max_digits=10)),
                ('center_longitude', models.DecimalField(decimal_places=8, help_text='Center longitude of the delivery zone', max_digits=11)),
                ('radius_km', models.DecimalField(decimal_places=2, help_text='Radius of the delivery zone in kilometers', max_digits=5)),
                ('base_delivery_fee', models.DecimalField(decimal_places=2, help_text='Base delivery fee for this zone', max_digits=8)),
                ('estimated_delivery_time', models.PositiveIntegerField(help_text='Estimated delivery time in minutes')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this delivery zone is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Zone',
                'verbose_name_plural': 'Delivery Zones',
                'ordering': ['name'],
            },
        ),
    ]
