# Generated by Django 5.2.5 on 2025-10-15 14:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_orderriderassignment_riderassignment_riderlocation_and_more'),
        ('orders', '0004_add_prescription_fields_and_chat'),
        ('users', '0009_add_rider_dispatch_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(help_text='Unique offer identifier (e.g., OFFER_DQ_ORD123_1)', max_length=50, unique=True)),
                ('is_batch', models.BooleanField(default=False, help_text='Whether this is a batch offer (multiple orders)')),
                ('orders_count', models.PositiveIntegerField(default=1, help_text='Number of orders in this offer')),
                ('total_earnings', models.DecimalField(decimal_places=2, help_text='Total rider earnings for this offer', max_digits=10)),
                ('pickup_distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Distance from rider current location to pickup', max_digits=5, null=True)),
                ('offered_at', models.DateTimeField(auto_now_add=True, help_text='When offer was sent to rider')),
                ('expires_at', models.DateTimeField(help_text='When offer expires (typically 30-45 seconds from offered_at)')),
                ('responded_at', models.DateTimeField(blank=True, help_text='When rider responded (accepted or rejected)', null=True)),
                ('response_time_seconds', models.DecimalField(blank=True, decimal_places=2, help_text='How many seconds rider took to respond', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Response'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('timeout', 'Timed Out'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of this offer', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, help_text='Reason for rejection (if rider rejected)', max_length=100, null=True)),
                ('attempt_number', models.PositiveIntegerField(default=1, help_text='Which attempt this is (1st rider, 2nd rider, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_assignment', models.ForeignKey(blank=True, help_text='Batch assignment (if batched orders)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_offers', to='delivery.riderassignment')),
                ('order', models.ForeignKey(blank=True, help_text='Single order (if not a batch)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_offers', to='orders.order')),
                ('rider', models.ForeignKey(help_text='Rider receiving this offer', on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_offers', to='users.rider')),
            ],
            options={
                'verbose_name': 'Dispatch Offer',
                'verbose_name_plural': 'Dispatch Offers',
                'db_table': 'dispatch_offer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_id', models.CharField(help_text='Unique queue identifier (e.g., DQ_ORD20251012_123)', max_length=50, unique=True)),
                ('is_batch', models.BooleanField(default=False, help_text='Whether dispatching a batch of orders')),
                ('priority_level', models.PositiveIntegerField(default=1, help_text='Priority level (1=highest, 10=lowest)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('total_attempts', models.PositiveIntegerField(default=0, help_text='Number of riders this has been offered to')),
                ('max_attempts', models.PositiveIntegerField(default=10, help_text='Maximum number of riders to try before giving up')),
                ('status', models.CharField(choices=[('pending', 'Pending Dispatch'), ('dispatching', 'Currently Being Offered to Riders'), ('assigned', 'Successfully Assigned to Rider'), ('failed', 'All Riders Rejected/Timeout'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of dispatch queue', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, help_text='When first dispatch attempt started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When dispatch was completed (assigned or failed)', null=True)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of times dispatch was retried after failure')),
                ('fee_increased', models.BooleanField(default=False, help_text='Whether delivery fee was increased to incentivize acceptance')),
                ('batch_assignment', models.ForeignKey(blank=True, help_text='Batch assignment to dispatch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_queue', to='delivery.riderassignment')),
                ('current_offer', models.ForeignKey(blank=True, help_text='Currently active offer for this queue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_queue', to='delivery.dispatchoffer')),
                ('order', models.ForeignKey(blank=True, help_text='Single order to dispatch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_queue', to='orders.order')),
            ],
            options={
                'verbose_name': 'Dispatch Queue',
                'verbose_name_plural': 'Dispatch Queues',
                'db_table': 'dispatch_queue',
                'ordering': ['priority_level', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dispatchoffer',
            index=models.Index(fields=['offer_id'], name='idx_offer_id'),
        ),
        migrations.AddIndex(
            model_name='dispatchoffer',
            index=models.Index(fields=['rider'], name='idx_offer_rider'),
        ),
        migrations.AddIndex(
            model_name='dispatchoffer',
            index=models.Index(fields=['order'], name='idx_offer_order'),
        ),
        migrations.AddIndex(
            model_name='dispatchoffer',
            index=models.Index(fields=['status'], name='idx_offer_status'),
        ),
        migrations.AddIndex(
            model_name='dispatchoffer',
            index=models.Index(fields=['expires_at'], name='idx_offer_expires'),
        ),
        migrations.AddIndex(
            model_name='dispatchoffer',
            index=models.Index(fields=['attempt_number'], name='idx_offer_attempt'),
        ),
        migrations.AddIndex(
            model_name='dispatchqueue',
            index=models.Index(fields=['queue_id'], name='idx_queue_id'),
        ),
        migrations.AddIndex(
            model_name='dispatchqueue',
            index=models.Index(fields=['order'], name='idx_queue_order'),
        ),
        migrations.AddIndex(
            model_name='dispatchqueue',
            index=models.Index(fields=['status'], name='idx_queue_status'),
        ),
        migrations.AddIndex(
            model_name='dispatchqueue',
            index=models.Index(fields=['priority_level'], name='idx_queue_priority'),
        ),
        migrations.AddIndex(
            model_name='dispatchqueue',
            index=models.Index(fields=['created_at'], name='idx_queue_created'),
        ),
    ]
