# Generated by Django 5.2.5 on 2025-10-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_add_dispatch_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderriderassignment',
            name='proof_of_delivery_url',
            field=models.URLField(blank=True, help_text='URL to proof of delivery photo (Cloudinary)', max_length=1000, null=True),
        ),
    ]
