# Generated by Django 5.2.5 on 2025-08-17 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('parent_house', "Parent's House"), ('other', 'Other')], default='home', help_text='Address label for identification', max_length=50)),
                ('is_default', models.BooleanField(default=False, help_text='Marks as default delivery address')),
                ('street_address', models.TextField(help_text='Full street address with landmarks')),
                ('barangay', models.CharField(help_text='Barangay information', max_length=100)),
                ('city', models.CharField(default='Iligan City', help_text='City name', max_length=50)),
                ('province', models.CharField(default='Lanao del Norte', help_text='Province name', max_length=50)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='GPS latitude coordinate', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='GPS longitude coordinate', max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('building_name', models.CharField(blank=True, help_text='Building or establishment name', max_length=255, null=True)),
                ('floor_number', models.CharField(blank=True, help_text='Floor number or level', max_length=20, null=True)),
                ('unit_number', models.CharField(blank=True, help_text='Unit or room number', max_length=20, null=True)),
                ('landmark', models.CharField(blank=True, help_text='Nearby landmark for easy identification', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'address',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
