# Generated by Django 5.2.5 on 2025-08-17 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(help_text='Customer who owns this address', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.customer'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['customer'], name='idx_address_customer'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['is_default'], name='idx_address_default'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city'], name='idx_address_city'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['barangay'], name='idx_address_barangay'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('customer', 'label'), name='unique_customer_address_label'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='valid_latitude'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='valid_longitude'),
        ),
    ]
