"""
Django settings for pharmago project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables
# Try to load from backend/.env first, then fall back to root .env
env_path = Path(__file__).parent.parent / '.env'
if env_path.exists():
    load_dotenv(env_path)
else:
    load_dotenv()  # Fallback to default behavior

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-your-secret-key-here')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# Dev performance toggles (safe defaults for development only)
ENABLE_API_USAGE_MW = os.getenv('ENABLE_API_USAGE_MW', '0') == '1'
ENABLE_SYSTEM_HEALTH_MW = os.getenv('ENABLE_SYSTEM_HEALTH_MW', '0') == '1'
DISABLE_THROTTLE = os.getenv('DISABLE_THROTTLE', '1') == '1'
LIGHT_LOGGING = os.getenv('LIGHT_LOGGING', '1') == '1'
DISABLE_FILE_LOG = os.getenv('DISABLE_FILE_LOG', '1') == '1'
EMAIL_CONSOLE = os.getenv('EMAIL_CONSOLE', '1') == '1'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',') if os.getenv('ALLOWED_HOSTS') else [
    'localhost', '127.0.0.1', '0.0.0.0', 'testserver'
]

# In development, allow all hosts so mobile devices on LAN can reach the backend
if DEBUG:
    ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_spectacular',
    'channels',  # WebSocket support for dispatch system
    'cloudinary_storage',  # Cloudinary for file storage
    'cloudinary',
    
    # Local apps
    'api.apps.ApiConfig',
    'api.users.apps.UsersConfig',
    'api.locations.apps.LocationsConfig',
    'api.pharmacies.apps.PharmaciesConfig',
    'api.inventory.apps.InventoryConfig',
    'api.orders.apps.OrdersConfig',
    'api.delivery.apps.DeliveryConfig',
    'api.payments.apps.PaymentsConfig',
    'api.notifications.apps.NotificationsConfig',
    'api.chat.apps.ChatConfig',
    'api.global_api.apps.GlobalApiConfig',
    'api.search.apps.SearchConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Add heavier middlewares only in production by default, or opt-in via env in dev
if (not DEBUG) or ENABLE_API_USAGE_MW:
    MIDDLEWARE.append('api.global_api.middleware.ApiUsageTrackingMiddleware')
if (not DEBUG) or ENABLE_SYSTEM_HEALTH_MW:
    MIDDLEWARE.append('api.global_api.middleware.SystemHealthMiddleware')

ROOT_URLCONF = 'pharmago.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pharmago.wsgi.application'
ASGI_APPLICATION = 'pharmago.asgi.application'

# Channels Configuration (WebSocket Support)
CHANNEL_LAYERS = {
    'default': {
        # Use in-memory channel layer for development
        # For production with multiple workers, use Redis:
        # 'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'pharmago'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'postgres'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5434'),
        
        # Optimized for ASGI/async environment with WebSockets
        # Reuse connections for better performance while preventing exhaustion
        'CONN_MAX_AGE': 300,  # 5 minutes - reuse connections (was 10s, too aggressive)
        'CONN_HEALTH_CHECKS': True,  # Validate connections before reuse (Django 4.1+)
        
        # Connection pool and timeout settings
        'OPTIONS': {
            'connect_timeout': 10,  # Connection attempt timeout (was 5s, increased for stability)
            'options': '-c statement_timeout=30000',  # 30s query timeout to prevent hanging queries
        }
    }
}

# Async database access configuration
# Ensure sync_to_async uses the correct thread-local connection handling
DATABASES['default']['ATOMIC_REQUESTS'] = False  # Don't wrap views in transactions for async


# Custom User Model
# https://docs.djangoproject.com/en/5.2/topics/auth/customizing/#substituting-a-custom-user-model

AUTH_USER_MODEL = 'users.User'

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'api.users.authentication.CustomAuthenticationBackend',
    'api.users.authentication.PhoneAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Use absolute path prefix so admin static assets resolve as /static/... instead of relative paths
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'





# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'api.authentication.AdminTokenAuthentication',  # Temporarily disabled - using middleware instead
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',  # Temporarily disabled
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.IsAuthenticated',  # Temporarily disabled for testing
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        'burst': '20/minute',
    },
}

# In development, disable throttling to reduce cache/Redis work unless explicitly enabled
if DEBUG and DISABLE_THROTTLE:
    REST_FRAMEWORK['DEFAULT_THROTTLE_CLASSES'] = []
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {}

# JWT Settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    
    'JTI_CLAIM': 'jti',
    
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "https://pharmago.up.railway.app",  # Production pharmacy dashboard - checked first for performance
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost:8081",  # Expo web development server
    "http://127.0.0.1:8081",  # Expo web development server
]

# Add production frontend URLs if specified
if os.getenv('FRONTEND_URL'):
    frontend_url = os.getenv('FRONTEND_URL')
    if frontend_url not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(frontend_url)

# Add additional CORS origins from environment (comma-separated)
additional_origins = os.getenv('CORS_ALLOWED_ORIGINS', '')
if additional_origins:
    for origin in additional_origins.split(','):
        origin = origin.strip()
        if origin and origin not in CORS_ALLOWED_ORIGINS:
            CORS_ALLOWED_ORIGINS.append(origin)

CORS_ALLOW_CREDENTIALS = True

# Additional CORS settings for mobile app development
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Allow all origins in development
CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'api': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)

# Lighter logging and no file logging in development by default
if DEBUG and LIGHT_LOGGING:
    try:
        LOGGING['loggers']['api']['level'] = 'INFO'
    except Exception:
        pass
    try:
        LOGGING['root']['level'] = 'WARNING'
    except Exception:
        pass

if DEBUG and DISABLE_FILE_LOG:
    LOGGING['handlers'].pop('file', None)
    if 'django' in LOGGING.get('loggers', {}):
        LOGGING['loggers']['django']['handlers'] = ['console']
    if 'api' in LOGGING.get('loggers', {}):
        LOGGING['loggers']['api']['handlers'] = ['console']

# AWS S3 Settings (Optional - only if using S3 instead of Cloudinary)
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKgirET_NAME')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'ap-southeast-2')

# Google Maps API Configuration
GOOGLE_MAPS_API_KEY = os.getenv('GOOGLE_MAPS_API_KEY')

# Cloudinary Configuration
if os.getenv('CLOUDINARY_CLOUD_NAME'):
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
        'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
        'API_SECRET': os.getenv('CLOUDINARY_API_SECRET')
    }
    # Use Cloudinary for media file storage in production
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Email settings (Gmail SMTP with new app password)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'sotidelivery@gmail.com'
EMAIL_HOST_PASSWORD = 'lbhl lwyt kjlc cxby'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'PharmGo <noreply@pharmago.com>')
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

# In development, avoid SMTP latency by default
if DEBUG and EMAIL_CONSOLE:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Session settings
SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# Security settings (for development - adjust for production)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# File upload settings - Increased for multiple file uploads
FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB per file
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB total request size
FILE_UPLOAD_PERMISSIONS = 0o644

# Cache settings (for development)
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# Use Redis for session storage
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

# Celery settings (if using async tasks)
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Admin authentication now uses database users only
# No environment variable fallback needed

# API Documentation with drf-spectacular
SPECTACULAR_SETTINGS = {
    'TITLE': 'PharmaGo API',
    'DESCRIPTION': 'Comprehensive medicine delivery platform API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/v1/',
    'TAGS': [
        {'name': 'users', 'description': 'User management endpoints'},
        {'name': 'orders', 'description': 'Order management endpoints'},
        {'name': 'inventory', 'description': 'Medicine inventory endpoints'},
        {'name': 'delivery', 'description': 'Delivery and rider management'},
        {'name': 'payments', 'description': 'Payment processing endpoints'},
        {'name': 'notifications', 'description': 'Notification system endpoints'},
        {'name': 'chat', 'description': 'Real-time chat system endpoints'},
        {'name': 'global-api', 'description': 'Global API infrastructure endpoints'},
    ],
}

# Import production settings if in production mode
if not DEBUG and os.path.exists(os.path.join(BASE_DIR, 'pharmago', 'settings_production.py')):
    try:
        from .settings_production import *
    except ImportError:
        pass