# Generated by Django 5.2.5 on 2024-01-01 00:00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('database', 'Database'), ('cache', 'Cache'), ('storage', 'File Storage'), ('external_apis', 'External APIs'), ('email', 'Email Service'), ('celery', 'Background Tasks'), ('overall', 'Overall System')], max_length=50)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical'), ('maintenance', 'Maintenance')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in milliseconds', null=True)),
            ],
            options={
                'verbose_name': 'System Health',
                'verbose_name_plural': 'System Health',
                'ordering': ['-last_check'],
            },
        ),
        migrations.CreateModel(
            name='ApiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('response_time', models.FloatField(help_text='Response time in milliseconds')),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_size', models.IntegerField(blank=True, help_text='Request size in bytes', null=True)),
                ('response_size', models.IntegerField(blank=True, help_text='Response size in bytes', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Usage',
                'verbose_name_plural': 'API Usage',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GlobalSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('cross_model', 'Cross-Model Search'), ('specific_model', 'Specific Model Search'), ('advanced_filter', 'Advanced Filtering'), ('bulk_operation', 'Bulk Operation')], max_length=20)),
                ('query', models.TextField()),
                ('models_searched', models.JSONField(default=list, help_text='List of models included in search')),
                ('results_count', models.IntegerField()),
                ('execution_time', models.FloatField(help_text='Search execution time in milliseconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Global Search Log',
                'verbose_name_plural': 'Global Search Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BulkOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('create', 'Bulk Create'), ('update', 'Bulk Update'), ('delete', 'Bulk Delete'), ('export', 'Bulk Export'), ('import', 'Bulk Import')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_items', models.IntegerField()),
                ('processed_items', models.IntegerField(default=0)),
                ('successful_items', models.IntegerField(default=0)),
                ('failed_items', models.IntegerField(default=0)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, help_text='Total execution time in seconds', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Operation Log',
                'verbose_name_plural': 'Bulk Operation Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='systemhealth',
            index=models.Index(fields=['component', 'last_check'], name='global_api__componen_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusage',
            index=models.Index(fields=['user', 'timestamp'], name='global_api__user_id_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusage',
            index=models.Index(fields=['endpoint', 'timestamp'], name='global_api__endpoin_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='apiusage',
            index=models.Index(fields=['status_code', 'timestamp'], name='global_api__status__123456_idx'),
        ),
        migrations.AddIndex(
            model_name='globalsearchlog',
            index=models.Index(fields=['user', 'timestamp'], name='global_api__user_id_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='globalsearchlog',
            index=models.Index(fields=['search_type', 'timestamp'], name='global_api__search__123456_idx'),
        ),
        migrations.AddIndex(
            model_name='globalsearchlog',
            index=models.Index(fields=['query', 'timestamp'], name='global_api__query_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkoperationlog',
            index=models.Index(fields=['user', 'started_at'], name='global_api__user_id_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkoperationlog',
            index=models.Index(fields=['operation_type', 'started_at'], name='global_api__operati_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkoperationlog',
            index=models.Index(fields=['status', 'started_at'], name='global_api__status__123456_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='systemhealth',
            unique_together={('component', 'last_check')},
        ),
    ]
