# Generated by Django 5.2.5 on 2025-09-13 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='estimated_delivery',
        ),
    ]
