# Generated by Django 5.2.5 on 2025-09-18 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_estimated_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prescription_image_url',
            field=models.URLField(blank=True, help_text='URL of uploaded prescription image', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='prescription_notes',
            field=models.TextField(blank=True, help_text='Pharmacist notes about prescription', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='prescription_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Prescription verification status', max_length=50),
        ),
        migrations.CreateModel(
            name='OrderChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Chat message content')),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('image', 'Image Message'), ('system', 'System Message')], default='text', help_text='Type of message', max_length=50)),
                ('image_url', models.URLField(blank=True, help_text='URL of attached image (for image messages)', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether message has been read by recipient')),
                ('read_at', models.DateTimeField(blank=True, help_text='When message was read', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(help_text='Order this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='orders.order')),
                ('sender', models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Chat Message',
                'verbose_name_plural': 'Order Chat Messages',
                'db_table': 'order_chat_message',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['order'], name='idx_chat_order'), models.Index(fields=['sender'], name='idx_chat_sender'), models.Index(fields=['created_at'], name='idx_chat_created'), models.Index(fields=['is_read'], name='idx_chat_read')],
            },
        ),
    ]
