# Generated by Django 5.1.7 on 2025-10-22 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_prescription_fields_and_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='senior_citizen_id_image',
            field=models.URLField(blank=True, help_text='Cloudinary URL for senior citizen ID photo', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='senior_discount_notes',
            field=models.TextField(blank=True, help_text='Pharmacy notes about senior discount verification', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='senior_discount_requested',
            field=models.BooleanField(default=False, help_text='Whether customer requested senior citizen discount'),
        ),
        migrations.AddField(
            model_name='order',
            name='senior_discount_review_date',
            field=models.DateTimeField(blank=True, help_text='When senior discount was reviewed', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='senior_discount_reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Pharmacy user who reviewed the senior discount', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senior_discount_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='senior_discount_status',
            field=models.CharField(choices=[('not_requested', 'Not Requested'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_requested', help_text='Pharmacy approval status for senior discount', max_length=20),
        ),
    ]
