# Generated by Django 5.2.5 on 2025-09-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_business_documents_and_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='file_url',
            field=models.URLField(blank=True, help_text='S3 URL of uploaded file.', null=True),
        ),
    ]
