# Generated by Django 5.2.5 on 2025-09-08 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userdocument_file_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryLoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Unique token for login.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(help_text='When this token expires.')),
                ('is_used', models.BooleanField(default=False, help_text='Whether this token has been used.')),
                ('used_at', models.DateTimeField(blank=True, help_text='When this token was used.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User associated with this token.', on_delete=django.db.models.deletion.CASCADE, related_name='temporary_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Temporary Login Token',
                'verbose_name_plural': 'Temporary Login Tokens',
                'db_table': 'temporary_login_tokens',
                'indexes': [models.Index(fields=['token'], name='idx_token_value'), models.Index(fields=['expires_at'], name='idx_token_expires'), models.Index(fields=['is_used'], name='idx_token_used')],
            },
        ),
    ]
