# Generated by Django 5.2.5 on 2025-09-19 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_temporarylogintoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(help_text='Associated user account.', on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='user',
            field=models.OneToOneField(help_text='Associated user account.', on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rider',
            name='user',
            field=models.OneToOneField(help_text='Associated user account.', on_delete=django.db.models.deletion.CASCADE, related_name='rider', to=settings.AUTH_USER_MODEL),
        ),
    ]
