# Generated by Django 5.2.5 on 2025-10-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customer_user_alter_pharmacy_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='document_file',
            field=models.FileField(blank=True, help_text='Uploaded document file (optional if file_url is provided).', null=True, upload_to='user_documents/%Y/%m/%d/'),
        ),
    ]
