# Generated by Django 5.2.5 on 2025-10-15 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_make_document_file_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='acceptance_rate',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Percentage of dispatch offers accepted (0-100%).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='rider',
            name='activity_status',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online - Available for Orders'), ('busy', 'Busy - Currently on Delivery'), ('break', 'On Break')], default='offline', help_text='Current activity status of rider for dispatch system.', max_length=20),
        ),
        migrations.AddField(
            model_name='rider',
            name='average_response_time',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average response time to dispatch offers in seconds.', max_digits=5),
        ),
        migrations.AddField(
            model_name='rider',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Current latitude coordinate (updated in real-time).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='rider',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Current longitude coordinate (updated in real-time).', max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='rider',
            name='last_seen_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time rider was active (updated every 30 seconds).'),
        ),
        migrations.AddField(
            model_name='rider',
            name='total_offers_accepted',
            field=models.PositiveIntegerField(default=0, help_text='Total dispatch offers accepted.'),
        ),
        migrations.AddField(
            model_name='rider',
            name='total_offers_received',
            field=models.PositiveIntegerField(default=0, help_text='Total dispatch offers received.'),
        ),
        migrations.AddField(
            model_name='rider',
            name='total_offers_rejected',
            field=models.PositiveIntegerField(default=0, help_text='Total dispatch offers rejected.'),
        ),
        migrations.AddField(
            model_name='rider',
            name='total_offers_timeout',
            field=models.PositiveIntegerField(default=0, help_text='Total dispatch offers that timed out.'),
        ),
        migrations.AddIndex(
            model_name='rider',
            index=models.Index(fields=['activity_status'], name='idx_rider_activity'),
        ),
        migrations.AddIndex(
            model_name='rider',
            index=models.Index(fields=['current_latitude', 'current_longitude'], name='idx_rider_location'),
        ),
        migrations.AddIndex(
            model_name='rider',
            index=models.Index(fields=['acceptance_rate'], name='idx_rider_acceptance'),
        ),
    ]
