# Generated by Django 5.2.5 on 2025-08-17 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Notification title', max_length=255)),
                ('message', models.TextField(help_text='Notification content')),
                ('notification_type', models.CharField(choices=[('order_update', 'Order Update'), ('delivery', 'Delivery'), ('payment', 'Payment'), ('system', 'System'), ('promotion', 'Promotion'), ('security', 'Security'), ('verification', 'Verification'), ('support', 'Support')], default='system', help_text='Type of notification', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', help_text='Notification priority level', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of linked object', null=True)),
                ('delivery_methods', models.JSONField(default=list, help_text='Methods used to deliver this notification')),
                ('is_read', models.BooleanField(default=False, help_text='Read status')),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was read', null=True)),
                ('is_sent', models.BooleanField(default=False, help_text='Whether notification was sent')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When notification was sent', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional notification data', null=True)),
                ('action_url', models.URLField(blank=True, help_text='URL for notification action', max_length=500, null=True)),
                ('action_text', models.CharField(blank=True, help_text='Text for notification action button', max_length=100, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When notification expires', null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='When to send scheduled notification', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Content type for linked object', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
