# Generated by Django 5.2.5 on 2025-08-20 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatparticipant',
            name='user',
            field=models.ForeignKey(help_text='Participating user', on_delete=django.db.models.deletion.CASCADE, related_name='chat_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(help_text='Message sender', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='chat.chatparticipant'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='order',
            field=models.ForeignKey(help_text='Associated order', on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='orders.order'),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='room',
            field=models.ForeignKey(help_text='Chat room', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chat.chatroom'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(help_text='Chat room', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['order'], name='idx_chatroom_order'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['status'], name='idx_chatroom_status'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['last_activity'], name='idx_chatroom_activity'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['room'], name='idx_participant_room'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['user'], name='idx_participant_user'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['role'], name='idx_participant_role'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['is_active'], name='idx_participant_active'),
        ),
        migrations.AddConstraint(
            model_name='chatparticipant',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='unique_room_participant'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room'], name='idx_message_room'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender'], name='idx_message_sender'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['timestamp'], name='idx_message_timestamp'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['message_type'], name='idx_message_type'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['status'], name='idx_message_status'),
        ),
    ]
