# Generated by Django 5.2.5 on 2025-08-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyOperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='Day of the week', max_length=10)),
                ('open_time', models.TimeField(help_text='Opening time')),
                ('close_time', models.TimeField(help_text='Closing time')),
                ('is_closed', models.BooleanField(default=False, help_text='Whether pharmacy is closed on this day')),
            ],
            options={
                'verbose_name': 'Pharmacy Operating Hours',
                'verbose_name_plural': 'Pharmacy Operating Hours',
                'ordering': ['day_of_week'],
            },
        ),
    ]
