# Generated by Django 5.2.5 on 2025-08-17 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(help_text='Business name', max_length=255)),
                ('business_type', models.CharField(choices=[('independent', 'Independent Pharmacy'), ('chain', 'Chain Pharmacy'), ('hospital', 'Hospital Pharmacy'), ('clinic', 'Medical Clinic Pharmacy')], default='independent', help_text='Type of pharmacy business', max_length=50)),
                ('first_name', models.CharField(help_text="Owner's first name", max_length=100)),
                ('last_name', models.CharField(help_text="Owner's last name", max_length=100)),
                ('phone_number', models.CharField(help_text='Business contact number', max_length=20)),
                ('email', models.EmailField(help_text='Business email address', max_length=254)),
                ('valid_id', models.URLField(help_text="Owner's valid ID file path", max_length=255)),
                ('business_permit', models.URLField(help_text='Business permit file path', max_length=255)),
                ('license_document', models.URLField(help_text='Pharmacy license file path', max_length=255)),
                ('street_address', models.CharField(help_text='Business address', max_length=255)),
                ('city', models.CharField(default='Iligan City', help_text='City location', max_length=50)),
                ('province', models.CharField(default='Lanao del Norte', help_text='Province location', max_length=50)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='GPS latitude coordinate', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='GPS longitude coordinate', max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', help_text='Verification status', max_length=50)),
                ('date_status', models.DateTimeField(blank=True, help_text='Status change timestamp', null=True)),
                ('status_notes', models.TextField(blank=True, help_text='Notes about status change', null=True)),
                ('operating_hours', models.JSONField(blank=True, help_text='Business operating hours', null=True)),
                ('services_offered', models.JSONField(blank=True, help_text='Services offered by the pharmacy', null=True)),
                ('payment_methods', models.JSONField(blank=True, help_text='Accepted payment methods', null=True)),
                ('description', models.TextField(blank=True, help_text='Pharmacy description', null=True)),
                ('website', models.URLField(blank=True, help_text='Pharmacy website', max_length=255, null=True)),
                ('social_media', models.JSONField(blank=True, help_text='Social media links', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pharmacy',
                'verbose_name_plural': 'Pharmacies',
                'db_table': 'pharmacy',
                'ordering': ['-created_at'],
            },
        ),
    ]
