# Generated by Django 5.2.5 on 2025-08-20 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyoperatinghours',
            name='pharmacy',
            field=models.ForeignKey(help_text='Associated pharmacy', on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_operating_hours', to='users.pharmacy'),
        ),
        migrations.AlterUniqueTogether(
            name='pharmacyoperatinghours',
            unique_together={('pharmacy', 'day_of_week')},
        ),
    ]
