# Generated by Django 5.2.5 on 2025-08-17 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='user',
            field=models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['user'], name='idx_pharmacy_user'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['status'], name='idx_pharmacy_status'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['city'], name='idx_pharmacy_city'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['business_type'], name='idx_pharmacy_business_type'),
        ),
        migrations.AddConstraint(
            model_name='pharmacy',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='valid_pharmacy_latitude'),
        ),
        migrations.AddConstraint(
            model_name='pharmacy',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='valid_pharmacy_longitude'),
        ),
    ]
